module_perf = "Perf"

########
# Perf #
########
mt_perf_perf = "Performance"
md_perf_perf = "Print PyGDO performance metrics."
perf_version = "Version: %s"
perf_user = "User: %s(%s)"
perf_cpu = "CPU %s%% (%s threads)"
perf_mem = "Memory: %s"
perf_db = "DB (%sR/%sW/#%s/%.02fT)"
perf_code = "%s tot(%s max) GDTs / %s tot(%s max) GDOs / %s Mods(%s)"
